### ISSUE TITLE
How to adjust

### ISSUE THREAD

**Issue by abrasmelin** [Dreaming-Codes/nvidia_oc#10]
![nvidia_uv](https://github.com/user-attachments/assets/5e0e42d0-d045-4ecf-8f86-31e85f2326d3)
I undervolt my Nvidia card with these settings in windows msi afterburner. Can you help me to convert these into your scripts parameters please?

Thanks!

**Comment by Dreaming-Codes** [comment]
I have no idea, never used MSI Afterburner. And that's not the place to ask

**Comment by abrasmelin** [comment]
How can the script do undervolt? Maybe you can add some example usage on the mainpage ? 

Thanks

**Comment by Dreaming-Codes** [comment]
> How can the script do undervolt? Maybe you can add some example usage on the mainpage ? 
> 
> Thanks

I'm not sure NVML (the Nvidia SDK this tool uses under the hood) allows voltage regulation but I'll check tomorrow.
