### ISSUE TITLE
Add voltage changes support

### ISSUE THREAD

**Issue by dougg0k** [Dreaming-Codes/nvidia_oc#12]
Hi,

Can you add voltages setting support?

Current offered options seems to be related to frequency only. 

It would make easy to undervolt the gpu with it.

**Comment by Dreaming-Codes** [comment]
I'll check if NVML provides a way to do that soon™

**Comment by dougg0k** [comment]
https://www.reddit.com/r/linux_gaming/comments/17kx3vu/how_to_crudely_overclock_your_nvidia_gpu_on/

**Comment by dougg0k** [comment]
https://github.com/jacklul/nvml-scripts/tree/master/nvml-undervolt

**Comment by dougg0k** [comment]
A daemon could be a `--flag` as optional. But sure.

**Comment by dougg0k** [comment]
Also, this tool, doesnt seem to do anything more than you already can do with `nvidia-smi`. Maybe offering different functionality would be useful.
