### ISSUE TITLE
Add fan setting support

### ISSUE THREAD

**Issue by dougg0k** [Dreaming-Codes/nvidia_oc#13]
Hi,

Can you add fan setting support based on the temperature, like setting multiple points that would make better use of the GPU fan?

**Comment by Dreaming-Codes** [comment]
Please see closed feature requests before creating a new ones #9

**Comment by dougg0k** [comment]
https://github.com/jacklul/nvml-scripts/tree/master/nvml-fan-curve

**Comment by Dreaming-Codes** [comment]
> https://github.com/jacklul/nvml-scripts/tree/master/nvml-fan-curve

I know that's possible I've just said I'm not interested in implementing that since it would need a daemon and there are already a lot of software to manage GPUs fans.
