### ISSUE TITLE
Negative offsets

### ISSUE THREAD

**Issue by fyr77** [Dreaming-Codes/nvidia_oc#15]
Hi!

I have a somewhat strange request. My GPU is unstable if run on stock clocks, but works perfectly fine if slightly underclocked. Would it be possible to allow negative offsets in this application? 

Thanks!

**Comment by Dreaming-Codes** [comment]
Hi, I no longer have an Nvidia GPU but my app already takes i32 as input so if the Nvidia control library supports negative values it should just work.

**Comment by fyr77** [comment]
Huh, it works now. I could have sworn it crashed the last time I tried. 

Sorry for that, and thanks!
