### ISSUE TITLE
Failed to set GPU power limit: "Error code: 3"

### ISSUE THREAD

**Issue by lbetol** [Dreaming-Codes/nvidia_oc#3]
when executing the code, the error is displayed:

~]# ./nvidia_oc set --index 0 --power-limit 200000 --freq-offset 160 --mem-offset 850
thread 'main' panicked at src/main.rs:83:26:
Failed to set GPU power limit: "Error code: 3"
stack backtrace:
   0:     0x59f49f9fad05 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1e1a1972118942ad
   1:     0x59f49fa1c34b - core::fmt::write::hc090a2ffd6b28c4a
   2:     0x59f49f9f8cff - std::io::Write::write_fmt::h8898bac6ff039a23
   3:     0x59f49f9faade - std::sys_common::backtrace::print::ha96650907276675e
   4:     0x59f49f9fbd99 - std::panicking::default_hook::{{closure}}::h215c2a0a8346e0e0
   5:     0x59f49f9fbadd - std::panicking::default_hook::h207342be97478370
   6:     0x59f49f9fc233 - std::panicking::rust_panic_with_hook::hac8bdceee1e4fe2c
   7:     0x59f49f9fc114 - std::panicking::begin_panic_handler::{{closure}}::h00d785e82757ce3c
   8:     0x59f49f9fb1c9 - std::sys_common::backtrace::__rust_end_short_backtrace::h1628d957bcd06996
   9:     0x59f49f9fbe47 - rust_begin_unwind
  10:     0x59f49f92edf3 - core::panicking::panic_fmt::hdc63834ffaaefae5
  11:     0x59f49f92f206 - core::result::unwrap_failed::h82b551e0ff2b2176
  12:     0x59f49f943858 - nvidia_oc::main::h5d23fbf1455d3ebc
  13:     0x59f49f952cd3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h62cf2716c9e91ff3
  14:     0x59f49f953949 - std::rt::lang_start::{{closure}}::h84d874c721ca05fb
  15:     0x59f49f9f4110 - std::rt::lang_start_internal::h3ed4fe7b2f419135
  16:     0x59f49f946045 - main
  17:     0x7f795e878e08 - <unknown>
  18:     0x7f795e878ecc - __libc_start_main
  19:     0x59f49f92f3e5 - _start
  20:                0x0 - <unknown>

My config:
Laptop Lenovo Legion 5I
Intel I7-12700h
Nvidia RTX 3060
6.10.2-arch1-1
Endeavouros

**Comment by Dreaming-Codes** [comment]
According to the NVML api documentation error code 3 means that your gpu doesn't support changing the power limit.
https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceEnums.html#group__nvmlDeviceEnums_1g06fa9b5de08c6cc716fbf565e93dd3d0
