### ISSUE TITLE
Doesn't work on Fedora SIlverblue (Bluefin)

### ISSUE THREAD

**Issue by rashadgasimli** [Dreaming-Codes/nvidia_oc#5]
Hello. The script doesn't work, here is a terminal input/output:

```
> sudo ./nvidia_oc set --index 1 --power-limit 45000
thread 'main' panicked at src/main.rs:62:37:
Failed to initialize NVML: LibloadingError(DlOpen { desc: "libnvidia-ml.so: cannot open shared object file: No such file or directory" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Dreaming-Codes** [comment]
Which nvidia driver are you using?

**Comment by Dreaming-Codes** [comment]
I believe the required shared library is included in the CUDA toolkit package on Fedora. You can find more information on how to install it [here](https://rpmfusion.org/Howto/CUDA). However, I have never used Fedora or Fedora Silverblue, so you may need to do some additional research on your own.
