### ISSUE TITLE
[Feature Request] Add option to set target fan speed

### ISSUE THREAD

**Issue by palvarad** [Dreaming-Codes/nvidia_oc#9]
Hello,

Thanks for creating this tool! If is not outside the scope of the tool, would be possible to add the option to set the target fan speed?

A few weeks ago, I modified the 0.1.11 version of the tool to add that functionality. Attached is the code.
While it works, it was a trial and error process. I am not familiar with Rust, so there is the possibility that I did something incorrectly. The code sets the fan speed of all the fans to a specify speed.  Option one gets the number of fans dynamically while option two uses a set value. I added a new gpu_fan_speed Set and copied the format of the ifs and functions.

I tried to add the code to the description of the issue, but the format was wrong which is why I am attaching the snippets of code as a file.
I am not submitting as a PR as I have very little GitHub experience.

[gpu_fan_speed_changes.txt](https://github.com/user-attachments/files/17179402/gpu_fan_speed_changes.txt)

**Comment by Dreaming-Codes** [comment]
Hi, thanks for the interest in the project however I think it's outside the scope of the tool. There are already a lot of tools to control fan speeds such as https://gitlab.com/coolercontrol/coolercontrol

**Comment by dougg0k** [comment]
As much as so, direct control over it, wouldnt it help on the OC keep cooled in lower usage?
